// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/stream">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/files/conversations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/conversations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/files/conversations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/files/download/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/download/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/files/download/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/files/preview/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/preview/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/files/preview/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/conversations/[id]/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/conversations/[id]/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/conversations/[id]/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/conversations">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/migrate/legacy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/migrate/legacy">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/migrate/legacy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/sync/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/sync/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/sync/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/local/open/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/local/open">> = Specific
  const handler = {} as typeof import("../../src/app/api/local/open/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/models/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models">> = Specific
  const handler = {} as typeof import("../../src/app/api/models/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/uploads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads">> = Specific
  const handler = {} as typeof import("../../src/app/api/uploads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
